displayName=ChunkBlazer
author=btwinnn
description=ChunkBlazer is a Randomized, Automated, Task rolling, Area-Restricted, Plugin / Game Mode.
tags=chunk,chunkblazer,nuzlocke,challenge,task,region
version=1.0.5
plugins=com.chunkblazer.ChunkBlazerPlugin
build=standard
